# Generated by Django 4.2 on 2023-05-02 05:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0002_rename_romm_room"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="romms",
            new_name="rooms",
        ),
    ]
