# Generated by Django 4.2 on 2023-05-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0003_rename_romms_room_rooms"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="name",
            field=models.CharField(default="", max_length=180),
        ),
    ]
