# Generated by Django 4.2 on 2023-05-02 05:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0004_room_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name_plural": "Amenities"},
        ),
        migrations.RenameField(
            model_name="amenity",
            old_name="createdd_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="amenity",
            old_name="updatedd_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="createdd_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="updatedd_at",
            new_name="updated_at",
        ),
    ]
